// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TblAuthProvidersColumns holds the columns for the "tbl_auth_providers" table.
	TblAuthProvidersColumns = []*schema.Column{
		{Name: "id_int", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_by", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "updated_by", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "ip_address", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString, Size: 64},
		{Name: "display_name", Type: field.TypeString},
	}
	// TblAuthProvidersTable holds the schema information for the "tbl_auth_providers" table.
	TblAuthProvidersTable = &schema.Table{
		Name:       "tbl_auth_providers",
		Columns:    TblAuthProvidersColumns,
		PrimaryKey: []*schema.Column{TblAuthProvidersColumns[0]},
	}
	// TblAuthUsersColumns holds the columns for the "tbl_auth_users" table.
	TblAuthUsersColumns = []*schema.Column{
		{Name: "id_uuid", Type: field.TypeString, Unique: true, Size: 40},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_by", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "updated_by", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "ip_address", Type: field.TypeString, Nullable: true},
		{Name: "provider_user_id", Type: field.TypeString, Size: 255},
		{Name: "team_id", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "name", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "real_name", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "email", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "access_token", Type: field.TypeString, Size: 2147483647},
		{Name: "refresh_token", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "token_type", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "scope", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "raw_profile", Type: field.TypeJSON, Nullable: true},
		{Name: "provider_id", Type: field.TypeInt},
	}
	// TblAuthUsersTable holds the schema information for the "tbl_auth_users" table.
	TblAuthUsersTable = &schema.Table{
		Name:       "tbl_auth_users",
		Columns:    TblAuthUsersColumns,
		PrimaryKey: []*schema.Column{TblAuthUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tbl_auth_users_tbl_auth_providers_users",
				Columns:    []*schema.Column{TblAuthUsersColumns[20]},
				RefColumns: []*schema.Column{TblAuthProvidersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TblAuthProvidersTable,
		TblAuthUsersTable,
	}
)

func init() {
	TblAuthProvidersTable.Annotation = &entsql.Annotation{
		Table: "tbl_auth_providers",
	}
	TblAuthUsersTable.ForeignKeys[0].RefTable = TblAuthProvidersTable
	TblAuthUsersTable.Annotation = &entsql.Annotation{
		Table: "tbl_auth_users",
	}
}
