// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"auth/ent/entgen/authprovider"
	"auth/ent/entgen/authuser"
	"auth/ent/entgen/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthProviderQuery is the builder for querying AuthProvider entities.
type AuthProviderQuery struct {
	config
	ctx        *QueryContext
	order      []authprovider.OrderOption
	inters     []Interceptor
	predicates []predicate.AuthProvider
	withUsers  *AuthUserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AuthProviderQuery builder.
func (apq *AuthProviderQuery) Where(ps ...predicate.AuthProvider) *AuthProviderQuery {
	apq.predicates = append(apq.predicates, ps...)
	return apq
}

// Limit the number of records to be returned by this query.
func (apq *AuthProviderQuery) Limit(limit int) *AuthProviderQuery {
	apq.ctx.Limit = &limit
	return apq
}

// Offset to start from.
func (apq *AuthProviderQuery) Offset(offset int) *AuthProviderQuery {
	apq.ctx.Offset = &offset
	return apq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (apq *AuthProviderQuery) Unique(unique bool) *AuthProviderQuery {
	apq.ctx.Unique = &unique
	return apq
}

// Order specifies how the records should be ordered.
func (apq *AuthProviderQuery) Order(o ...authprovider.OrderOption) *AuthProviderQuery {
	apq.order = append(apq.order, o...)
	return apq
}

// QueryUsers chains the current query on the "users" edge.
func (apq *AuthProviderQuery) QueryUsers() *AuthUserQuery {
	query := (&AuthUserClient{config: apq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := apq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := apq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(authprovider.Table, authprovider.FieldID, selector),
			sqlgraph.To(authuser.Table, authuser.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, authprovider.UsersTable, authprovider.UsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(apq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AuthProvider entity from the query.
// Returns a *NotFoundError when no AuthProvider was found.
func (apq *AuthProviderQuery) First(ctx context.Context) (*AuthProvider, error) {
	nodes, err := apq.Limit(1).All(setContextOp(ctx, apq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{authprovider.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (apq *AuthProviderQuery) FirstX(ctx context.Context) *AuthProvider {
	node, err := apq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AuthProvider ID from the query.
// Returns a *NotFoundError when no AuthProvider ID was found.
func (apq *AuthProviderQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = apq.Limit(1).IDs(setContextOp(ctx, apq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{authprovider.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (apq *AuthProviderQuery) FirstIDX(ctx context.Context) int {
	id, err := apq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AuthProvider entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AuthProvider entity is found.
// Returns a *NotFoundError when no AuthProvider entities are found.
func (apq *AuthProviderQuery) Only(ctx context.Context) (*AuthProvider, error) {
	nodes, err := apq.Limit(2).All(setContextOp(ctx, apq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{authprovider.Label}
	default:
		return nil, &NotSingularError{authprovider.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (apq *AuthProviderQuery) OnlyX(ctx context.Context) *AuthProvider {
	node, err := apq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AuthProvider ID in the query.
// Returns a *NotSingularError when more than one AuthProvider ID is found.
// Returns a *NotFoundError when no entities are found.
func (apq *AuthProviderQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = apq.Limit(2).IDs(setContextOp(ctx, apq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{authprovider.Label}
	default:
		err = &NotSingularError{authprovider.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (apq *AuthProviderQuery) OnlyIDX(ctx context.Context) int {
	id, err := apq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AuthProviders.
func (apq *AuthProviderQuery) All(ctx context.Context) ([]*AuthProvider, error) {
	ctx = setContextOp(ctx, apq.ctx, ent.OpQueryAll)
	if err := apq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AuthProvider, *AuthProviderQuery]()
	return withInterceptors[[]*AuthProvider](ctx, apq, qr, apq.inters)
}

// AllX is like All, but panics if an error occurs.
func (apq *AuthProviderQuery) AllX(ctx context.Context) []*AuthProvider {
	nodes, err := apq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AuthProvider IDs.
func (apq *AuthProviderQuery) IDs(ctx context.Context) (ids []int, err error) {
	if apq.ctx.Unique == nil && apq.path != nil {
		apq.Unique(true)
	}
	ctx = setContextOp(ctx, apq.ctx, ent.OpQueryIDs)
	if err = apq.Select(authprovider.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (apq *AuthProviderQuery) IDsX(ctx context.Context) []int {
	ids, err := apq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (apq *AuthProviderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, apq.ctx, ent.OpQueryCount)
	if err := apq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, apq, querierCount[*AuthProviderQuery](), apq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (apq *AuthProviderQuery) CountX(ctx context.Context) int {
	count, err := apq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (apq *AuthProviderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, apq.ctx, ent.OpQueryExist)
	switch _, err := apq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entgen: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (apq *AuthProviderQuery) ExistX(ctx context.Context) bool {
	exist, err := apq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AuthProviderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (apq *AuthProviderQuery) Clone() *AuthProviderQuery {
	if apq == nil {
		return nil
	}
	return &AuthProviderQuery{
		config:     apq.config,
		ctx:        apq.ctx.Clone(),
		order:      append([]authprovider.OrderOption{}, apq.order...),
		inters:     append([]Interceptor{}, apq.inters...),
		predicates: append([]predicate.AuthProvider{}, apq.predicates...),
		withUsers:  apq.withUsers.Clone(),
		// clone intermediate query.
		sql:  apq.sql.Clone(),
		path: apq.path,
	}
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (apq *AuthProviderQuery) WithUsers(opts ...func(*AuthUserQuery)) *AuthProviderQuery {
	query := (&AuthUserClient{config: apq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	apq.withUsers = query
	return apq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AuthProvider.Query().
//		GroupBy(authprovider.FieldCreatedAt).
//		Aggregate(entgen.Count()).
//		Scan(ctx, &v)
func (apq *AuthProviderQuery) GroupBy(field string, fields ...string) *AuthProviderGroupBy {
	apq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AuthProviderGroupBy{build: apq}
	grbuild.flds = &apq.ctx.Fields
	grbuild.label = authprovider.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AuthProvider.Query().
//		Select(authprovider.FieldCreatedAt).
//		Scan(ctx, &v)
func (apq *AuthProviderQuery) Select(fields ...string) *AuthProviderSelect {
	apq.ctx.Fields = append(apq.ctx.Fields, fields...)
	sbuild := &AuthProviderSelect{AuthProviderQuery: apq}
	sbuild.label = authprovider.Label
	sbuild.flds, sbuild.scan = &apq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AuthProviderSelect configured with the given aggregations.
func (apq *AuthProviderQuery) Aggregate(fns ...AggregateFunc) *AuthProviderSelect {
	return apq.Select().Aggregate(fns...)
}

func (apq *AuthProviderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range apq.inters {
		if inter == nil {
			return fmt.Errorf("entgen: uninitialized interceptor (forgotten import entgen/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, apq); err != nil {
				return err
			}
		}
	}
	for _, f := range apq.ctx.Fields {
		if !authprovider.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entgen: invalid field %q for query", f)}
		}
	}
	if apq.path != nil {
		prev, err := apq.path(ctx)
		if err != nil {
			return err
		}
		apq.sql = prev
	}
	return nil
}

func (apq *AuthProviderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AuthProvider, error) {
	var (
		nodes       = []*AuthProvider{}
		_spec       = apq.querySpec()
		loadedTypes = [1]bool{
			apq.withUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AuthProvider).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AuthProvider{config: apq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, apq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := apq.withUsers; query != nil {
		if err := apq.loadUsers(ctx, query, nodes,
			func(n *AuthProvider) { n.Edges.Users = []*AuthUser{} },
			func(n *AuthProvider, e *AuthUser) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (apq *AuthProviderQuery) loadUsers(ctx context.Context, query *AuthUserQuery, nodes []*AuthProvider, init func(*AuthProvider), assign func(*AuthProvider, *AuthUser)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AuthProvider)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(authuser.FieldProviderID)
	}
	query.Where(predicate.AuthUser(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(authprovider.UsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProviderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "provider_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (apq *AuthProviderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := apq.querySpec()
	_spec.Node.Columns = apq.ctx.Fields
	if len(apq.ctx.Fields) > 0 {
		_spec.Unique = apq.ctx.Unique != nil && *apq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, apq.driver, _spec)
}

func (apq *AuthProviderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(authprovider.Table, authprovider.Columns, sqlgraph.NewFieldSpec(authprovider.FieldID, field.TypeInt))
	_spec.From = apq.sql
	if unique := apq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if apq.path != nil {
		_spec.Unique = true
	}
	if fields := apq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authprovider.FieldID)
		for i := range fields {
			if fields[i] != authprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := apq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := apq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := apq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := apq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (apq *AuthProviderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(apq.driver.Dialect())
	t1 := builder.Table(authprovider.Table)
	columns := apq.ctx.Fields
	if len(columns) == 0 {
		columns = authprovider.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if apq.sql != nil {
		selector = apq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if apq.ctx.Unique != nil && *apq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range apq.predicates {
		p(selector)
	}
	for _, p := range apq.order {
		p(selector)
	}
	if offset := apq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := apq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AuthProviderGroupBy is the group-by builder for AuthProvider entities.
type AuthProviderGroupBy struct {
	selector
	build *AuthProviderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (apgb *AuthProviderGroupBy) Aggregate(fns ...AggregateFunc) *AuthProviderGroupBy {
	apgb.fns = append(apgb.fns, fns...)
	return apgb
}

// Scan applies the selector query and scans the result into the given value.
func (apgb *AuthProviderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, apgb.build.ctx, ent.OpQueryGroupBy)
	if err := apgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuthProviderQuery, *AuthProviderGroupBy](ctx, apgb.build, apgb, apgb.build.inters, v)
}

func (apgb *AuthProviderGroupBy) sqlScan(ctx context.Context, root *AuthProviderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(apgb.fns))
	for _, fn := range apgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*apgb.flds)+len(apgb.fns))
		for _, f := range *apgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*apgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := apgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AuthProviderSelect is the builder for selecting fields of AuthProvider entities.
type AuthProviderSelect struct {
	*AuthProviderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aps *AuthProviderSelect) Aggregate(fns ...AggregateFunc) *AuthProviderSelect {
	aps.fns = append(aps.fns, fns...)
	return aps
}

// Scan applies the selector query and scans the result into the given value.
func (aps *AuthProviderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aps.ctx, ent.OpQuerySelect)
	if err := aps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuthProviderQuery, *AuthProviderSelect](ctx, aps.AuthProviderQuery, aps, aps.inters, v)
}

func (aps *AuthProviderSelect) sqlScan(ctx context.Context, root *AuthProviderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aps.fns))
	for _, fn := range aps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
