// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"auth/ent/entgen/authprovider"
	"auth/ent/entgen/authuser"
	"auth/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authproviderMixin := schema.AuthProvider{}.Mixin()
	authproviderMixinFields0 := authproviderMixin[0].Fields()
	_ = authproviderMixinFields0
	authproviderFields := schema.AuthProvider{}.Fields()
	_ = authproviderFields
	// authproviderDescCreatedAt is the schema descriptor for created_at field.
	authproviderDescCreatedAt := authproviderMixinFields0[1].Descriptor()
	// authprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	authprovider.DefaultCreatedAt = authproviderDescCreatedAt.Default.(func() time.Time)
	// authproviderDescUpdatedAt is the schema descriptor for updated_at field.
	authproviderDescUpdatedAt := authproviderMixinFields0[2].Descriptor()
	// authprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authprovider.DefaultUpdatedAt = authproviderDescUpdatedAt.Default.(func() time.Time)
	// authprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authprovider.UpdateDefaultUpdatedAt = authproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authproviderDescCreatedBy is the schema descriptor for created_by field.
	authproviderDescCreatedBy := authproviderMixinFields0[4].Descriptor()
	// authprovider.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	authprovider.CreatedByValidator = authproviderDescCreatedBy.Validators[0].(func(string) error)
	// authproviderDescUpdatedBy is the schema descriptor for updated_by field.
	authproviderDescUpdatedBy := authproviderMixinFields0[5].Descriptor()
	// authprovider.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	authprovider.UpdatedByValidator = authproviderDescUpdatedBy.Validators[0].(func(string) error)
	// authproviderDescDeletedBy is the schema descriptor for deleted_by field.
	authproviderDescDeletedBy := authproviderMixinFields0[6].Descriptor()
	// authprovider.DeletedByValidator is a validator for the "deleted_by" field. It is called by the builders before save.
	authprovider.DeletedByValidator = authproviderDescDeletedBy.Validators[0].(func(string) error)
	// authproviderDescName is the schema descriptor for name field.
	authproviderDescName := authproviderFields[0].Descriptor()
	// authprovider.NameValidator is a validator for the "name" field. It is called by the builders before save.
	authprovider.NameValidator = func() func(string) error {
		validators := authproviderDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// authproviderDescID is the schema descriptor for id field.
	authproviderDescID := authproviderMixinFields0[0].Descriptor()
	// authprovider.IDValidator is a validator for the "id" field. It is called by the builders before save.
	authprovider.IDValidator = authproviderDescID.Validators[0].(func(int) error)
	authuserMixin := schema.AuthUser{}.Mixin()
	authuserMixinFields0 := authuserMixin[0].Fields()
	_ = authuserMixinFields0
	authuserFields := schema.AuthUser{}.Fields()
	_ = authuserFields
	// authuserDescCreatedAt is the schema descriptor for created_at field.
	authuserDescCreatedAt := authuserMixinFields0[1].Descriptor()
	// authuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	authuser.DefaultCreatedAt = authuserDescCreatedAt.Default.(func() time.Time)
	// authuserDescUpdatedAt is the schema descriptor for updated_at field.
	authuserDescUpdatedAt := authuserMixinFields0[2].Descriptor()
	// authuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authuser.DefaultUpdatedAt = authuserDescUpdatedAt.Default.(func() time.Time)
	// authuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authuser.UpdateDefaultUpdatedAt = authuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authuserDescCreatedBy is the schema descriptor for created_by field.
	authuserDescCreatedBy := authuserMixinFields0[4].Descriptor()
	// authuser.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	authuser.CreatedByValidator = authuserDescCreatedBy.Validators[0].(func(string) error)
	// authuserDescUpdatedBy is the schema descriptor for updated_by field.
	authuserDescUpdatedBy := authuserMixinFields0[5].Descriptor()
	// authuser.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	authuser.UpdatedByValidator = authuserDescUpdatedBy.Validators[0].(func(string) error)
	// authuserDescDeletedBy is the schema descriptor for deleted_by field.
	authuserDescDeletedBy := authuserMixinFields0[6].Descriptor()
	// authuser.DeletedByValidator is a validator for the "deleted_by" field. It is called by the builders before save.
	authuser.DeletedByValidator = authuserDescDeletedBy.Validators[0].(func(string) error)
	// authuserDescProviderUserID is the schema descriptor for provider_user_id field.
	authuserDescProviderUserID := authuserFields[1].Descriptor()
	// authuser.ProviderUserIDValidator is a validator for the "provider_user_id" field. It is called by the builders before save.
	authuser.ProviderUserIDValidator = func() func(string) error {
		validators := authuserDescProviderUserID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider_user_id string) error {
			for _, fn := range fns {
				if err := fn(provider_user_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// authuserDescTeamID is the schema descriptor for team_id field.
	authuserDescTeamID := authuserFields[2].Descriptor()
	// authuser.TeamIDValidator is a validator for the "team_id" field. It is called by the builders before save.
	authuser.TeamIDValidator = authuserDescTeamID.Validators[0].(func(string) error)
	// authuserDescName is the schema descriptor for name field.
	authuserDescName := authuserFields[3].Descriptor()
	// authuser.NameValidator is a validator for the "name" field. It is called by the builders before save.
	authuser.NameValidator = authuserDescName.Validators[0].(func(string) error)
	// authuserDescRealName is the schema descriptor for real_name field.
	authuserDescRealName := authuserFields[4].Descriptor()
	// authuser.RealNameValidator is a validator for the "real_name" field. It is called by the builders before save.
	authuser.RealNameValidator = authuserDescRealName.Validators[0].(func(string) error)
	// authuserDescEmail is the schema descriptor for email field.
	authuserDescEmail := authuserFields[5].Descriptor()
	// authuser.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	authuser.EmailValidator = authuserDescEmail.Validators[0].(func(string) error)
	// authuserDescAccessToken is the schema descriptor for access_token field.
	authuserDescAccessToken := authuserFields[6].Descriptor()
	// authuser.AccessTokenValidator is a validator for the "access_token" field. It is called by the builders before save.
	authuser.AccessTokenValidator = authuserDescAccessToken.Validators[0].(func(string) error)
	// authuserDescTokenType is the schema descriptor for token_type field.
	authuserDescTokenType := authuserFields[8].Descriptor()
	// authuser.TokenTypeValidator is a validator for the "token_type" field. It is called by the builders before save.
	authuser.TokenTypeValidator = authuserDescTokenType.Validators[0].(func(string) error)
	// authuserDescID is the schema descriptor for id field.
	authuserDescID := authuserMixinFields0[0].Descriptor()
	// authuser.DefaultID holds the default value on creation for the id field.
	authuser.DefaultID = authuserDescID.Default.(func() string)
	// authuser.IDValidator is a validator for the "id" field. It is called by the builders before save.
	authuser.IDValidator = authuserDescID.Validators[0].(func(string) error)
}
