// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthProvider is the predicate function for authprovider builders.
type AuthProvider func(*sql.Selector)

// AuthUser is the predicate function for authuser builders.
type AuthUser func(*sql.Selector)
