// Code generated by mockery. DO NOT EDIT.
package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// IEnv is an autogenerated mock type for the IEnv type
type IEnv struct {
	mock.Mock
}

func (m *IEnv) Get(key string) string {
	args := m.Called(key)
	return args.String(0)
}

func (m *IEnv) SlackClientID() string {
	args := m.Called()
	return args.String(0)
}

func (m *IEnv) SlackClientSecret() string {
	args := m.Called()
	return args.String(0)
}

func (m *IEnv) SlackRedirectURI() string {
	args := m.Called()
	return args.String(0)
}

func (m *IEnv) GetDBHost() string {
	args := m.Called()
	return args.String(0)
}